### PR TITLE
Python 3 compatibility: use the implementer decorator

### PR DESCRIPTION
**Pull request by ale-rt**

### CODE REVIEW

**Comment by mgedmin** [comment]
LGTM.

Are there any more changes required for Python 3 compatibility?  If not, it'd be good to enable Python 3.4, 3.5, 3.6 in `.travis.yml` and add the corresponding trove classifiers to `setup.py`.

**Comment by mgedmin** [comment]
BTW have you signed the [Zope Foundation Committer Agreement](https://docs.zope.org/developer/becoming-a-committer.html)?  I'm not allowed to merge code from people who haven't signed it.  (And once you sign it, you'll get the committer bit that allows you to hit the nice big green Merge button yourself.)

**Review by mgedmin — APPROVED** [review]

**Comment by ale-rt** [comment]
Thanks @mgedmin I submitted the agreement.

We are not ready yet to start testing this package on Python 3, some dependencies still needs love, e.g. `z3c.objpath` and `zc.relation >= 1.0`. 
I plan to work on that when I have some spare time.

BTW I cannot find `z3c.objpath`. Maybe @mauritsvanrees can resurrect it somehow?

**Comment by mgedmin** [comment]
IIRC @jimfulton has a copy of the old Zope Subversion repository and could resurrect z3c.objpath if asked nicely.

(I also [have a copy](https://zope3.pov.lt/trac/browser/z3c.objpath), but I'm rusty on the process.)

**Comment by mauritsvanrees** [comment]
Sorry, I don't have any repository code from `z3c.objpath`.

**Comment by jimfulton** [comment]
z3c.objpath is now on github.

**Comment by ale-rt** [comment]
Thanks a lot to everybody :)
BTW I have been added to the zopefoundation organization, given @mgedmin approved this PR I am going to merge it

**Pull request merged**
